service: open-pension

package:
  individually: true
  exclude:


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: 'non-linux'

provider:
  name: aws
  runtime: python2.7
  region: us-west-2
  stage: dev
  environment:
    OUTPUT_DIRECTORY: directory
    SCHEMA_FILE: file

functions:
  process_k203:
    handler: app.handler.handler
    module: process_k203